site_name: Gemma Template
site_description: Gemma Template is a lightweight Python library for generating templates to fine-tune models like Gemma, LLaMa, and others. It supports multilingual frameworks, offers advanced customization, and ensures precise, dynamic template creation.
site_url: https://github.com/thewebscraping/gemma-template/

theme:
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'

repo_name: thewebscraping/gemma-template
repo_url: https://github.com/thewebscraping/gemma-template/
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Quickstart Guide: 'quickstart.md'
    - Load Dataset: 'load_dataset.md'
    - Generate Methods: 'generate_methods.md'
    - Custom Templates:
        - Default Templates: 'custom_templates/default_template.md'
        - Custom Templates: 'custom_templates/custom_template.md'
    - Models: 'models.md'
    - Benchmark: 'benchmark.md'

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
